import Link from "next/link";
import ArchImage from "@/components/ArchImage";
import { ReadMoreLabel } from "@/components/ReadMoreLink";
import { FAMILY_IMAGE_SLOT } from "@/lib/family-images";
import { IMAGES, type ImageSlot } from "@/lib/images";
import { waLink } from "@/lib/services";
import { SITE } from "@/lib/site";
import type { CategoryId, GroupId } from "@/lib/groups";
import { getRelatedFamilyPages, type FamilyPage as FamilyPageData } from "@/lib/family-pages";

// The exact sentence in content/treatment-descriptions.md that, when present, earns a
// family a second image next to it (queue row Q12 spec). Never added when the
// sentence is absent from the description.
const CONSULTATION_SENTENCE = "Every treatment starts with a free consultation.";

// One hero/category image slot per category (Q12 spec). Falls back to the matching
// group card slot when a category's own slot is not (yet) in lib/images.ts's IMAGES
// map -- that file is generated by the image pipeline (scripts/build-images.mjs) and
// is read-only from here.
const CATEGORY_IMAGE_SLOT: Record<CategoryId, ImageSlot> = {
  hifu: "story-hifu",
  laser: "cat-laser-skin",
  skin: "cat-skin",
  skinboosters: "cat-skinboosters",
  carboxy: "cat-carboxy",
  body: "body-card",
  hair: "story-laser-hair",
  facials: "face-card",
  massage: "wellness-card",
  "waxing-ladies": "cat-waxing-ladies",
  "waxing-men": "cat-waxing-men",
};

const GROUP_FALLBACK_SLOT: Record<GroupId, ImageSlot> = {
  face: "face-card",
  body: "body-card",
  laser: "laser-card",
  wellness: "wellness-card",
};

// One image slot per family page (lib/family-images.ts), used as that family's hero and as
// its card in every other page's "You may also like", so a built page never shows the same
// picture twice. A family with no entry there falls back to heroSlotFor (its category slot).

/** The family's own slot when it has one, otherwise its category slot. */
function slotForFamily(page: FamilyPageData): ImageSlot {
  const own = FAMILY_IMAGE_SLOT[page.slug];
  if (own && own in IMAGES) {
    return own;
  }
  return heroSlotFor(page.category, page.groupId);
}

// Categories whose treatments carry the age line in the Q12 spec's footer note.
// Deliberately excludes "facials".
const ADULTS_ONLY_CATEGORIES: ReadonlySet<CategoryId> = new Set([
  "hifu",
  "laser",
  "skin",
  "skinboosters",
  "carboxy",
  "body",
  "hair",
]);

/** The ImageSlot to pass to ArchImage for a category's hero/card image. Falls back
 * to the matching group card slot when a category's own slot is not (yet) a key of
 * IMAGES -- that map is generated by the image pipeline and read-only from here. */
function heroSlotFor(category: CategoryId, groupId: GroupId): ImageSlot {
  const wanted = CATEGORY_IMAGE_SLOT[category];
  if (wanted in IMAGES) {
    return wanted;
  }
  const fallback = GROUP_FALLBACK_SLOT[groupId];
  // Build-time signal only (see scripts/check-family-pages.mjs and the executor
  // report): names the missing slot so the image pipeline's own row can pick it up.
  console.warn(
    `[FamilyPage] image slot "${wanted}" (category "${category}") is not in lib/images.ts IMAGES; falling back to "${fallback}"`,
  );
  return fallback;
}

function breadcrumbJsonLd(page: FamilyPageData) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Treatments",
        item: `${SITE.url}/treatments/`,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: page.groupLabel,
        item: `${SITE.url}/treatments/#${page.groupId}`,
      },
      {
        "@type": "ListItem",
        position: 3,
        name: page.title,
        item: `${SITE.url}/treatments/${page.slug}/`,
      },
    ],
  };
}

function serviceJsonLd(page: FamilyPageData) {
  const json: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Service",
    name: page.title,
    provider: {
      "@type": "HealthAndBeautyBusiness",
      name: SITE.name,
      address: SITE.address,
    },
  };
  if (page.priced.length > 0) {
    json.offers = page.priced.map((row) => ({
      "@type": "Offer",
      price: row.priceGbp,
      priceCurrency: "GBP",
    }));
  }
  return json;
}

function RelatedCard({ page }: { page: FamilyPageData }) {
  const slot = slotForFamily(page);
  return (
    <Link
      href={`/treatments/${page.slug}/`}
      className="group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-oak focus-visible:ring-offset-2 focus-visible:ring-offset-cream rounded-arch"
    >
      <ArchImage
        slot={slot}
        aria-hidden
        sizes="(min-width: 640px) 33vw, 50vw"
        className="w-full"
      />
      <p className="mt-3 font-display text-lg text-espresso group-hover:text-oak">
        {page.title}
      </p>
      <ReadMoreLabel className="mt-1">Read more</ReadMoreLabel>
    </Link>
  );
}

export default function FamilyPage({ page }: { page: FamilyPageData }) {
  const heroSlot = slotForFamily(page);
  const hasConsultationLine = page.paragraphs.some((p) => p.includes(CONSULTATION_SENTENCE));
  const related = getRelatedFamilyPages(page.slug, 3);

  return (
    <main className="bg-cream">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd(page)) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceJsonLd(page)) }}
      />

      <section className="mx-auto max-w-6xl px-4 pt-6 md:px-6">
        <nav aria-label="Breadcrumb">
          <ol className="flex flex-wrap items-center gap-2 text-sm text-walnut">
            <li>
              <Link href="/treatments/" className="hover:text-oak">
                Treatments
              </Link>
            </li>
            <li aria-hidden className="text-beige">
              /
            </li>
            <li>
              <Link href={`/treatments/#${page.groupId}`} className="hover:text-oak">
                {page.groupLabel}
              </Link>
            </li>
            <li aria-hidden className="text-beige">
              /
            </li>
            <li aria-current="page" className="text-cocoa">
              {page.title}
            </li>
          </ol>
        </nav>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-8 md:px-6 md:py-12">
        <div className="grid items-center gap-8 lg:grid-cols-[1.2fr_1fr]">
          <ArchImage
            slot={heroSlot}
            priority
            sizes="(min-width: 1024px) 55vw, 100vw"
            className="order-first w-full lg:order-none"
          />
          <div>
            <h1 className="rise-in font-display text-4xl text-espresso md:text-5xl">{page.title}</h1>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-4 md:px-6">
        <div className="reveal max-w-3xl space-y-4 text-cocoa">
          {page.paragraphs.map((paragraph, i) => (
            <p key={i}>{paragraph}</p>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-8 md:px-6">
        {page.priced.length > 0 ? (
          <ul className="reveal divide-y divide-beige">
            {page.priced.map((row) => (
              <li
                key={row.slug}
                className="flex flex-wrap items-center justify-between gap-x-6 gap-y-2 py-4"
              >
                <div className="min-w-0">
                  <p className="text-espresso">{row.name}</p>
                  {row.duration ? <p className="text-walnut text-sm">{row.duration}</p> : null}
                </div>
                <div className="flex items-center gap-4">
                  {row.priceGbp !== null ? (
                    <span className="tabular text-espresso whitespace-nowrap">
                      {`${row.priceFrom ? "From " : ""}£${row.priceGbp}`}
                    </span>
                  ) : null}
                  <a
                    href={row.waHref}
                    target="_blank"
                    rel="noopener"
                    aria-label={row.waAriaLabel}
                    className="pill inline-block whitespace-nowrap rounded-full border border-oak px-4 py-2 text-sm text-oak hover:bg-oak hover:text-white"
                  >
                    Ask on WhatsApp
                  </a>
                </div>
              </li>
            ))}
          </ul>
        ) : (
          <a
            href={waLink(page.title, page.slug)}
            target="_blank"
            rel="noopener"
            className="pill inline-block rounded-full bg-oak px-6 py-3 text-white hover:opacity-90"
          >
            Ask for a quote on WhatsApp
          </a>
        )}
      </section>

      {hasConsultationLine ? (
        <section className="mx-auto max-w-6xl px-4 py-8 md:px-6">
          <div className="reveal grid items-center gap-8 lg:grid-cols-[1fr_1.2fr]">
            <ArchImage
              slot="step-2-consultation"
              sizes="(min-width: 1024px) 45vw, 100vw"
              className="order-first w-full lg:order-none"
            />
            <p className="font-display text-2xl text-espresso md:text-3xl">
              {CONSULTATION_SENTENCE}
            </p>
          </div>
        </section>
      ) : null}

      <section className="mx-auto max-w-6xl px-4 py-8 md:px-6">
        <p className="border-t border-beige pt-8 text-walnut">
          The price shown is the price you pay.
          {ADULTS_ONLY_CATEGORIES.has(page.category)
            ? " Aesthetic treatments are for adults aged 18 and over."
            : ""}
        </p>
      </section>

      {related.length > 0 ? (
        <section className="mx-auto max-w-6xl px-4 py-12 md:px-6">
          <h2 className="font-display text-2xl text-espresso">You may also like</h2>
          <div className="reveal mt-6 grid grid-cols-2 gap-6 sm:grid-cols-3">
            {related.map((relatedPage) => (
              <RelatedCard key={relatedPage.slug} page={relatedPage} />
            ))}
          </div>
        </section>
      ) : null}
    </main>
  );
}
