// Generated by scripts/build-images.mjs. Do not hand-edit.
// Source of truth: images-src/manifest.json

export interface ImageSrcset {
  avif: string;
  webp: string;
  jpg: string;
}

export interface ImageEntry {
  alt: string;
  ratio: string;
  width: number;
  height: number;
  srcset: ImageSrcset;
  fallback: string;
}

export type ImageSlot = "home-hero" | "face-card" | "body-card" | "laser-card" | "wellness-card" | "step-1-message" | "step-2-consultation" | "step-3-treatment" | "step-4-aftercare" | "contact-welcome" | "story-hifu" | "story-facials" | "story-body-contouring" | "story-laser-hair" | "room-warm" | "room-trolley" | "room-analyser" | "room-couch";

export const IMAGES: Record<ImageSlot, ImageEntry> = {
  "home-hero": {
    alt: "Woman lying back, eyes closed, as a therapist's hands apply cream to her cheek",
    ratio: "3:2",
    width: 800,
    height: 533,
    srcset: {
      avif: "/img/gen/home-hero-480.avif 480w, /img/gen/home-hero-800.avif 800w",
      webp: "/img/gen/home-hero-480.webp 480w, /img/gen/home-hero-800.webp 800w",
      jpg: "/img/gen/home-hero-480.jpg 480w, /img/gen/home-hero-800.jpg 800w",
    },
    fallback: "/img/gen/home-hero-800.jpg",
  },
  "face-card": {
    alt: "Close view of a relaxed face as fingertips move along the cheekbone",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/face-card-480.avif 480w, /img/gen/face-card-800.avif 800w",
      webp: "/img/gen/face-card-480.webp 480w, /img/gen/face-card-800.webp 800w",
      jpg: "/img/gen/face-card-480.jpg 480w, /img/gen/face-card-800.jpg 800w",
    },
    fallback: "/img/gen/face-card-800.jpg",
  },
  "body-card": {
    alt: "Hands pressing along a client's lower back while lying face down under a towel",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/body-card-480.avif 480w, /img/gen/body-card-800.avif 800w",
      webp: "/img/gen/body-card-480.webp 480w, /img/gen/body-card-800.webp 800w",
      jpg: "/img/gen/body-card-480.jpg 480w, /img/gen/body-card-800.jpg 800w",
    },
    fallback: "/img/gen/body-card-800.jpg",
  },
  "laser-card": {
    alt: "Seated woman in eyewear and a robe, therapist holding a device to her arm",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/laser-card-480.avif 480w, /img/gen/laser-card-800.avif 800w",
      webp: "/img/gen/laser-card-480.webp 480w, /img/gen/laser-card-800.webp 800w",
      jpg: "/img/gen/laser-card-480.jpg 480w, /img/gen/laser-card-800.jpg 800w",
    },
    fallback: "/img/gen/laser-card-800.jpg",
  },
  "wellness-card": {
    alt: "Hands pressing across a client's shoulders while lying face down, warm light",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/wellness-card-480.avif 480w, /img/gen/wellness-card-800.avif 800w",
      webp: "/img/gen/wellness-card-480.webp 480w, /img/gen/wellness-card-800.webp 800w",
      jpg: "/img/gen/wellness-card-480.jpg 480w, /img/gen/wellness-card-800.jpg 800w",
    },
    fallback: "/img/gen/wellness-card-800.jpg",
  },
  "step-1-message": {
    alt: "Hands holding a phone with an unreadable screen, resting on a soft cushion",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/step-1-message-480.avif 480w, /img/gen/step-1-message-800.avif 800w",
      webp: "/img/gen/step-1-message-480.webp 480w, /img/gen/step-1-message-800.webp 800w",
      jpg: "/img/gen/step-1-message-480.jpg 480w, /img/gen/step-1-message-800.jpg 800w",
    },
    fallback: "/img/gen/step-1-message-800.jpg",
  },
  "step-2-consultation": {
    alt: "Two women smiling in conversation, one holding a notebook and pen",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/step-2-consultation-480.avif 480w, /img/gen/step-2-consultation-800.avif 800w",
      webp: "/img/gen/step-2-consultation-480.webp 480w, /img/gen/step-2-consultation-800.webp 800w",
      jpg: "/img/gen/step-2-consultation-480.jpg 480w, /img/gen/step-2-consultation-800.jpg 800w",
    },
    fallback: "/img/gen/step-2-consultation-800.jpg",
  },
  "step-3-treatment": {
    alt: "Therapist placing a warm stone along a client's back, face out of frame",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/step-3-treatment-480.avif 480w, /img/gen/step-3-treatment-800.avif 800w",
      webp: "/img/gen/step-3-treatment-480.webp 480w, /img/gen/step-3-treatment-800.webp 800w",
      jpg: "/img/gen/step-3-treatment-480.jpg 480w, /img/gen/step-3-treatment-800.jpg 800w",
    },
    fallback: "/img/gen/step-3-treatment-800.jpg",
  },
  "step-4-aftercare": {
    alt: "Woman in a robe smiling while holding a cup of tea",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/step-4-aftercare-480.avif 480w, /img/gen/step-4-aftercare-800.avif 800w",
      webp: "/img/gen/step-4-aftercare-480.webp 480w, /img/gen/step-4-aftercare-800.webp 800w",
      jpg: "/img/gen/step-4-aftercare-480.jpg 480w, /img/gen/step-4-aftercare-800.jpg 800w",
    },
    fallback: "/img/gen/step-4-aftercare-800.jpg",
  },
  "contact-welcome": {
    alt: "Two women smiling across a curved wooden reception desk",
    ratio: "3:2",
    width: 1200,
    height: 800,
    srcset: {
      avif: "/img/gen/contact-welcome-480.avif 480w, /img/gen/contact-welcome-800.avif 800w, /img/gen/contact-welcome-1200.avif 1200w",
      webp: "/img/gen/contact-welcome-480.webp 480w, /img/gen/contact-welcome-800.webp 800w, /img/gen/contact-welcome-1200.webp 1200w",
      jpg: "/img/gen/contact-welcome-480.jpg 480w, /img/gen/contact-welcome-800.jpg 800w, /img/gen/contact-welcome-1200.jpg 1200w",
    },
    fallback: "/img/gen/contact-welcome-800.jpg",
  },
  "story-hifu": {
    alt: "Woman lying back, eyes closed, as a handheld device is held to her jaw",
    ratio: "3:2",
    width: 1200,
    height: 800,
    srcset: {
      avif: "/img/gen/story-hifu-480.avif 480w, /img/gen/story-hifu-800.avif 800w, /img/gen/story-hifu-1200.avif 1200w",
      webp: "/img/gen/story-hifu-480.webp 480w, /img/gen/story-hifu-800.webp 800w, /img/gen/story-hifu-1200.webp 1200w",
      jpg: "/img/gen/story-hifu-480.jpg 480w, /img/gen/story-hifu-800.jpg 800w, /img/gen/story-hifu-1200.jpg 1200w",
    },
    fallback: "/img/gen/story-hifu-800.jpg",
  },
  "story-facials": {
    alt: "Therapist brushing a cream mask onto a relaxed, smiling woman's cheek",
    ratio: "3:2",
    width: 1200,
    height: 800,
    srcset: {
      avif: "/img/gen/story-facials-480.avif 480w, /img/gen/story-facials-800.avif 800w, /img/gen/story-facials-1200.avif 1200w",
      webp: "/img/gen/story-facials-480.webp 480w, /img/gen/story-facials-800.webp 800w, /img/gen/story-facials-1200.webp 1200w",
      jpg: "/img/gen/story-facials-480.jpg 480w, /img/gen/story-facials-800.jpg 800w, /img/gen/story-facials-1200.jpg 1200w",
    },
    fallback: "/img/gen/story-facials-800.jpg",
  },
  "story-body-contouring": {
    alt: "Two women looking at a tablet together, its screen not readable",
    ratio: "3:2",
    width: 1200,
    height: 800,
    srcset: {
      avif: "/img/gen/story-body-contouring-480.avif 480w, /img/gen/story-body-contouring-800.avif 800w, /img/gen/story-body-contouring-1200.avif 1200w",
      webp: "/img/gen/story-body-contouring-480.webp 480w, /img/gen/story-body-contouring-800.webp 800w, /img/gen/story-body-contouring-1200.webp 1200w",
      jpg: "/img/gen/story-body-contouring-480.jpg 480w, /img/gen/story-body-contouring-800.jpg 800w, /img/gen/story-body-contouring-1200.jpg 1200w",
    },
    fallback: "/img/gen/story-body-contouring-800.jpg",
  },
  "story-laser-hair": {
    alt: "A therapist in gloves moves a handheld device along a client's lower leg",
    ratio: "3:2",
    width: 1200,
    height: 800,
    srcset: {
      avif: "/img/gen/story-laser-hair-480.avif 480w, /img/gen/story-laser-hair-800.avif 800w, /img/gen/story-laser-hair-1200.avif 1200w",
      webp: "/img/gen/story-laser-hair-480.webp 480w, /img/gen/story-laser-hair-800.webp 800w, /img/gen/story-laser-hair-1200.webp 1200w",
      jpg: "/img/gen/story-laser-hair-480.jpg 480w, /img/gen/story-laser-hair-800.jpg 800w, /img/gen/story-laser-hair-1200.jpg 1200w",
    },
    fallback: "/img/gen/story-laser-hair-800.jpg",
  },
  "room-warm": {
    alt: "A treatment room at Pure Essentials London with a wood-slat wall and couch",
    ratio: "4:5",
    width: 1200,
    height: 1500,
    srcset: {
      avif: "/img/gen/room-warm-480.avif 480w, /img/gen/room-warm-800.avif 800w, /img/gen/room-warm-1200.avif 1200w",
      webp: "/img/gen/room-warm-480.webp 480w, /img/gen/room-warm-800.webp 800w, /img/gen/room-warm-1200.webp 1200w",
      jpg: "/img/gen/room-warm-480.jpg 480w, /img/gen/room-warm-800.jpg 800w, /img/gen/room-warm-1200.jpg 1200w",
    },
    fallback: "/img/gen/room-warm-800.jpg",
  },
  "room-trolley": {
    alt: "A treatment room at Pure Essentials London with a trolley of products",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/room-trolley-480.avif 480w, /img/gen/room-trolley-800.avif 800w",
      webp: "/img/gen/room-trolley-480.webp 480w, /img/gen/room-trolley-800.webp 800w",
      jpg: "/img/gen/room-trolley-480.jpg 480w, /img/gen/room-trolley-800.jpg 800w",
    },
    fallback: "/img/gen/room-trolley-800.jpg",
  },
  "room-analyser": {
    alt: "A treatment room at Pure Essentials London with white cabinetry and a couch",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/room-analyser-480.avif 480w, /img/gen/room-analyser-800.avif 800w",
      webp: "/img/gen/room-analyser-480.webp 480w, /img/gen/room-analyser-800.webp 800w",
      jpg: "/img/gen/room-analyser-480.jpg 480w, /img/gen/room-analyser-800.jpg 800w",
    },
    fallback: "/img/gen/room-analyser-800.jpg",
  },
  "room-couch": {
    alt: "A treatment room at Pure Essentials London with rolled towels on the couch",
    ratio: "4:5",
    width: 800,
    height: 1000,
    srcset: {
      avif: "/img/gen/room-couch-480.avif 480w, /img/gen/room-couch-800.avif 800w",
      webp: "/img/gen/room-couch-480.webp 480w, /img/gen/room-couch-800.webp 800w",
      jpg: "/img/gen/room-couch-480.jpg 480w, /img/gen/room-couch-800.jpg 800w",
    },
    fallback: "/img/gen/room-couch-800.jpg",
  },
};
