// Generated by scripts/build-images.mjs. Do not hand-edit.
// Source of truth: images-src/manifest.json

export interface ImageSrcset {
  avif: string;
  webp: string;
  jpg: string;
}

export interface ImageEntry {
  alt: string;
  ratio: string;
  width: number;
  height: number;
  srcset: ImageSrcset;
  fallback: string;
}

export type ImageSlot = "home-hero" | "face-card" | "body-card" | "laser-card" | "wellness-card" | "step-1-message" | "step-2-consultation" | "step-3-treatment" | "step-4-aftercare" | "contact-welcome" | "story-hifu" | "story-facials" | "story-body-contouring" | "story-laser-hair" | "room-warm" | "room-trolley" | "room-analyser" | "room-couch" | "cat-laser-skin" | "cat-skin" | "cat-skinboosters" | "cat-carboxy" | "cat-waxing-ladies" | "cat-waxing-men" | "fam-hifu-face" | "fam-cryotherapy" | "fam-light-platform" | "fam-ipl" | "fam-pico-laser" | "fam-tattoo-removal" | "fam-gold-microneedling" | "fam-microneedling" | "fam-chemical-peel" | "fam-radiofrequency" | "fam-skin-booster-body" | "fam-skin-booster-face" | "fam-skin-booster-hydration" | "fam-fat-reduction" | "fam-muscle-toning" | "fam-hifu-body" | "fam-laser-hair" | "fam-hydrating-facial" | "fam-sensitive-skin-facial" | "fam-microdermabrasion" | "fam-botanical-facial";

export const IMAGES: Record<ImageSlot, ImageEntry> = {
  "home-hero": {
    alt: "Woman lying back, eyes closed, as a therapist's hands apply cream to her cheek",
    ratio: "3:2",
    width: 1170,
    height: 780,
    srcset: {
      avif: "/img/gen/home-hero-480.avif 480w, /img/gen/home-hero-800.avif 800w, /img/gen/home-hero-1170.avif 1170w",
      webp: "/img/gen/home-hero-480.webp 480w, /img/gen/home-hero-800.webp 800w, /img/gen/home-hero-1170.webp 1170w",
      jpg: "/img/gen/home-hero-480.jpg 480w, /img/gen/home-hero-800.jpg 800w, /img/gen/home-hero-1170.jpg 1170w",
    },
    fallback: "/img/gen/home-hero-800.jpg",
  },
  "face-card": {
    alt: "Close view of a relaxed face as fingertips move along the cheekbone",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/face-card-480.avif 480w, /img/gen/face-card-800.avif 800w, /img/gen/face-card-922.avif 922w",
      webp: "/img/gen/face-card-480.webp 480w, /img/gen/face-card-800.webp 800w, /img/gen/face-card-922.webp 922w",
      jpg: "/img/gen/face-card-480.jpg 480w, /img/gen/face-card-800.jpg 800w, /img/gen/face-card-922.jpg 922w",
    },
    fallback: "/img/gen/face-card-800.jpg",
  },
  "body-card": {
    alt: "Hands pressing along a client's lower back while lying face down under a towel",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/body-card-480.avif 480w, /img/gen/body-card-800.avif 800w, /img/gen/body-card-922.avif 922w",
      webp: "/img/gen/body-card-480.webp 480w, /img/gen/body-card-800.webp 800w, /img/gen/body-card-922.webp 922w",
      jpg: "/img/gen/body-card-480.jpg 480w, /img/gen/body-card-800.jpg 800w, /img/gen/body-card-922.jpg 922w",
    },
    fallback: "/img/gen/body-card-800.jpg",
  },
  "laser-card": {
    alt: "Seated woman in eyewear and a robe, therapist holding a device to her arm",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/laser-card-480.avif 480w, /img/gen/laser-card-800.avif 800w, /img/gen/laser-card-922.avif 922w",
      webp: "/img/gen/laser-card-480.webp 480w, /img/gen/laser-card-800.webp 800w, /img/gen/laser-card-922.webp 922w",
      jpg: "/img/gen/laser-card-480.jpg 480w, /img/gen/laser-card-800.jpg 800w, /img/gen/laser-card-922.jpg 922w",
    },
    fallback: "/img/gen/laser-card-800.jpg",
  },
  "wellness-card": {
    alt: "Hands pressing across a client's shoulders while lying face down, warm light",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/wellness-card-480.avif 480w, /img/gen/wellness-card-800.avif 800w, /img/gen/wellness-card-922.avif 922w",
      webp: "/img/gen/wellness-card-480.webp 480w, /img/gen/wellness-card-800.webp 800w, /img/gen/wellness-card-922.webp 922w",
      jpg: "/img/gen/wellness-card-480.jpg 480w, /img/gen/wellness-card-800.jpg 800w, /img/gen/wellness-card-922.jpg 922w",
    },
    fallback: "/img/gen/wellness-card-800.jpg",
  },
  "step-1-message": {
    alt: "Hands holding a phone with an unreadable screen, resting on a soft cushion",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/step-1-message-480.avif 480w, /img/gen/step-1-message-800.avif 800w, /img/gen/step-1-message-922.avif 922w",
      webp: "/img/gen/step-1-message-480.webp 480w, /img/gen/step-1-message-800.webp 800w, /img/gen/step-1-message-922.webp 922w",
      jpg: "/img/gen/step-1-message-480.jpg 480w, /img/gen/step-1-message-800.jpg 800w, /img/gen/step-1-message-922.jpg 922w",
    },
    fallback: "/img/gen/step-1-message-800.jpg",
  },
  "step-2-consultation": {
    alt: "Two women smiling in conversation, one holding a notebook and pen",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/step-2-consultation-480.avif 480w, /img/gen/step-2-consultation-800.avif 800w, /img/gen/step-2-consultation-922.avif 922w",
      webp: "/img/gen/step-2-consultation-480.webp 480w, /img/gen/step-2-consultation-800.webp 800w, /img/gen/step-2-consultation-922.webp 922w",
      jpg: "/img/gen/step-2-consultation-480.jpg 480w, /img/gen/step-2-consultation-800.jpg 800w, /img/gen/step-2-consultation-922.jpg 922w",
    },
    fallback: "/img/gen/step-2-consultation-800.jpg",
  },
  "step-3-treatment": {
    alt: "Therapist placing a warm stone along a client's back, face out of frame",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/step-3-treatment-480.avif 480w, /img/gen/step-3-treatment-800.avif 800w, /img/gen/step-3-treatment-922.avif 922w",
      webp: "/img/gen/step-3-treatment-480.webp 480w, /img/gen/step-3-treatment-800.webp 800w, /img/gen/step-3-treatment-922.webp 922w",
      jpg: "/img/gen/step-3-treatment-480.jpg 480w, /img/gen/step-3-treatment-800.jpg 800w, /img/gen/step-3-treatment-922.jpg 922w",
    },
    fallback: "/img/gen/step-3-treatment-800.jpg",
  },
  "step-4-aftercare": {
    alt: "Woman in a robe smiling while holding a cup of tea",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/step-4-aftercare-480.avif 480w, /img/gen/step-4-aftercare-800.avif 800w, /img/gen/step-4-aftercare-922.avif 922w",
      webp: "/img/gen/step-4-aftercare-480.webp 480w, /img/gen/step-4-aftercare-800.webp 800w, /img/gen/step-4-aftercare-922.webp 922w",
      jpg: "/img/gen/step-4-aftercare-480.jpg 480w, /img/gen/step-4-aftercare-800.jpg 800w, /img/gen/step-4-aftercare-922.jpg 922w",
    },
    fallback: "/img/gen/step-4-aftercare-800.jpg",
  },
  "contact-welcome": {
    alt: "Two women smiling across a curved wooden reception desk",
    ratio: "3:2",
    width: 1264,
    height: 843,
    srcset: {
      avif: "/img/gen/contact-welcome-480.avif 480w, /img/gen/contact-welcome-800.avif 800w, /img/gen/contact-welcome-1200.avif 1200w, /img/gen/contact-welcome-1264.avif 1264w",
      webp: "/img/gen/contact-welcome-480.webp 480w, /img/gen/contact-welcome-800.webp 800w, /img/gen/contact-welcome-1200.webp 1200w, /img/gen/contact-welcome-1264.webp 1264w",
      jpg: "/img/gen/contact-welcome-480.jpg 480w, /img/gen/contact-welcome-800.jpg 800w, /img/gen/contact-welcome-1200.jpg 1200w, /img/gen/contact-welcome-1264.jpg 1264w",
    },
    fallback: "/img/gen/contact-welcome-800.jpg",
  },
  "story-hifu": {
    alt: "Woman lying back, eyes closed, as a handheld device is held to her jaw",
    ratio: "3:2",
    width: 1264,
    height: 843,
    srcset: {
      avif: "/img/gen/story-hifu-480.avif 480w, /img/gen/story-hifu-800.avif 800w, /img/gen/story-hifu-1200.avif 1200w, /img/gen/story-hifu-1264.avif 1264w",
      webp: "/img/gen/story-hifu-480.webp 480w, /img/gen/story-hifu-800.webp 800w, /img/gen/story-hifu-1200.webp 1200w, /img/gen/story-hifu-1264.webp 1264w",
      jpg: "/img/gen/story-hifu-480.jpg 480w, /img/gen/story-hifu-800.jpg 800w, /img/gen/story-hifu-1200.jpg 1200w, /img/gen/story-hifu-1264.jpg 1264w",
    },
    fallback: "/img/gen/story-hifu-800.jpg",
  },
  "story-facials": {
    alt: "Therapist brushing a cream mask onto a relaxed, smiling woman's cheek",
    ratio: "3:2",
    width: 1264,
    height: 843,
    srcset: {
      avif: "/img/gen/story-facials-480.avif 480w, /img/gen/story-facials-800.avif 800w, /img/gen/story-facials-1200.avif 1200w, /img/gen/story-facials-1264.avif 1264w",
      webp: "/img/gen/story-facials-480.webp 480w, /img/gen/story-facials-800.webp 800w, /img/gen/story-facials-1200.webp 1200w, /img/gen/story-facials-1264.webp 1264w",
      jpg: "/img/gen/story-facials-480.jpg 480w, /img/gen/story-facials-800.jpg 800w, /img/gen/story-facials-1200.jpg 1200w, /img/gen/story-facials-1264.jpg 1264w",
    },
    fallback: "/img/gen/story-facials-800.jpg",
  },
  "story-body-contouring": {
    alt: "Two women looking at a tablet together, its screen not readable",
    ratio: "3:2",
    width: 1264,
    height: 843,
    srcset: {
      avif: "/img/gen/story-body-contouring-480.avif 480w, /img/gen/story-body-contouring-800.avif 800w, /img/gen/story-body-contouring-1200.avif 1200w, /img/gen/story-body-contouring-1264.avif 1264w",
      webp: "/img/gen/story-body-contouring-480.webp 480w, /img/gen/story-body-contouring-800.webp 800w, /img/gen/story-body-contouring-1200.webp 1200w, /img/gen/story-body-contouring-1264.webp 1264w",
      jpg: "/img/gen/story-body-contouring-480.jpg 480w, /img/gen/story-body-contouring-800.jpg 800w, /img/gen/story-body-contouring-1200.jpg 1200w, /img/gen/story-body-contouring-1264.jpg 1264w",
    },
    fallback: "/img/gen/story-body-contouring-800.jpg",
  },
  "story-laser-hair": {
    alt: "A therapist in gloves moves a handheld device along a client's lower leg",
    ratio: "3:2",
    width: 1264,
    height: 843,
    srcset: {
      avif: "/img/gen/story-laser-hair-480.avif 480w, /img/gen/story-laser-hair-800.avif 800w, /img/gen/story-laser-hair-1200.avif 1200w, /img/gen/story-laser-hair-1264.avif 1264w",
      webp: "/img/gen/story-laser-hair-480.webp 480w, /img/gen/story-laser-hair-800.webp 800w, /img/gen/story-laser-hair-1200.webp 1200w, /img/gen/story-laser-hair-1264.webp 1264w",
      jpg: "/img/gen/story-laser-hair-480.jpg 480w, /img/gen/story-laser-hair-800.jpg 800w, /img/gen/story-laser-hair-1200.jpg 1200w, /img/gen/story-laser-hair-1264.jpg 1264w",
    },
    fallback: "/img/gen/story-laser-hair-800.jpg",
  },
  "room-warm": {
    alt: "A treatment room at Pure Essentials London with a wood-slat wall and couch",
    ratio: "4:5",
    width: 1200,
    height: 1500,
    srcset: {
      avif: "/img/gen/room-warm-480.avif 480w, /img/gen/room-warm-800.avif 800w, /img/gen/room-warm-1200.avif 1200w",
      webp: "/img/gen/room-warm-480.webp 480w, /img/gen/room-warm-800.webp 800w, /img/gen/room-warm-1200.webp 1200w",
      jpg: "/img/gen/room-warm-480.jpg 480w, /img/gen/room-warm-800.jpg 800w, /img/gen/room-warm-1200.jpg 1200w",
    },
    fallback: "/img/gen/room-warm-800.jpg",
  },
  "room-trolley": {
    alt: "A treatment room at Pure Essentials London with a trolley of products",
    ratio: "4:5",
    width: 980,
    height: 1225,
    srcset: {
      avif: "/img/gen/room-trolley-480.avif 480w, /img/gen/room-trolley-800.avif 800w, /img/gen/room-trolley-980.avif 980w",
      webp: "/img/gen/room-trolley-480.webp 480w, /img/gen/room-trolley-800.webp 800w, /img/gen/room-trolley-980.webp 980w",
      jpg: "/img/gen/room-trolley-480.jpg 480w, /img/gen/room-trolley-800.jpg 800w, /img/gen/room-trolley-980.jpg 980w",
    },
    fallback: "/img/gen/room-trolley-800.jpg",
  },
  "room-analyser": {
    alt: "A treatment room at Pure Essentials London with white cabinetry and a couch",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/room-analyser-480.avif 480w, /img/gen/room-analyser-800.avif 800w, /img/gen/room-analyser-922.avif 922w",
      webp: "/img/gen/room-analyser-480.webp 480w, /img/gen/room-analyser-800.webp 800w, /img/gen/room-analyser-922.webp 922w",
      jpg: "/img/gen/room-analyser-480.jpg 480w, /img/gen/room-analyser-800.jpg 800w, /img/gen/room-analyser-922.jpg 922w",
    },
    fallback: "/img/gen/room-analyser-800.jpg",
  },
  "room-couch": {
    alt: "A treatment room at Pure Essentials London with rolled towels on the couch",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/room-couch-480.avif 480w, /img/gen/room-couch-800.avif 800w, /img/gen/room-couch-922.avif 922w",
      webp: "/img/gen/room-couch-480.webp 480w, /img/gen/room-couch-800.webp 800w, /img/gen/room-couch-922.webp 922w",
      jpg: "/img/gen/room-couch-480.jpg 480w, /img/gen/room-couch-800.jpg 800w, /img/gen/room-couch-922.jpg 922w",
    },
    fallback: "/img/gen/room-couch-800.jpg",
  },
  "cat-laser-skin": {
    alt: "Woman lying back in eyewear as gloved hands hold a device near her cheek",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/cat-laser-skin-480.avif 480w, /img/gen/cat-laser-skin-800.avif 800w, /img/gen/cat-laser-skin-922.avif 922w",
      webp: "/img/gen/cat-laser-skin-480.webp 480w, /img/gen/cat-laser-skin-800.webp 800w, /img/gen/cat-laser-skin-922.webp 922w",
      jpg: "/img/gen/cat-laser-skin-480.jpg 480w, /img/gen/cat-laser-skin-800.jpg 800w, /img/gen/cat-laser-skin-922.jpg 922w",
    },
    fallback: "/img/gen/cat-laser-skin-800.jpg",
  },
  "cat-skin": {
    alt: "Woman lying back, eyes closed, a gloved hand holding a device to her cheek",
    ratio: "4:5",
    width: 817,
    height: 1021,
    srcset: {
      avif: "/img/gen/cat-skin-480.avif 480w, /img/gen/cat-skin-800.avif 800w, /img/gen/cat-skin-817.avif 817w",
      webp: "/img/gen/cat-skin-480.webp 480w, /img/gen/cat-skin-800.webp 800w, /img/gen/cat-skin-817.webp 817w",
      jpg: "/img/gen/cat-skin-480.jpg 480w, /img/gen/cat-skin-800.jpg 800w, /img/gen/cat-skin-817.jpg 817w",
    },
    fallback: "/img/gen/cat-skin-800.jpg",
  },
  "cat-skinboosters": {
    alt: "Two women seated, one holding a hand mirror, the other writing in a notebook",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/cat-skinboosters-480.avif 480w, /img/gen/cat-skinboosters-800.avif 800w, /img/gen/cat-skinboosters-922.avif 922w",
      webp: "/img/gen/cat-skinboosters-480.webp 480w, /img/gen/cat-skinboosters-800.webp 800w, /img/gen/cat-skinboosters-922.webp 922w",
      jpg: "/img/gen/cat-skinboosters-480.jpg 480w, /img/gen/cat-skinboosters-800.jpg 800w, /img/gen/cat-skinboosters-922.jpg 922w",
    },
    fallback: "/img/gen/cat-skinboosters-800.jpg",
  },
  "cat-carboxy": {
    alt: "Two smiling women looking together at pages in an open book",
    ratio: "4:5",
    width: 663,
    height: 829,
    srcset: {
      avif: "/img/gen/cat-carboxy-480.avif 480w, /img/gen/cat-carboxy-663.avif 663w",
      webp: "/img/gen/cat-carboxy-480.webp 480w, /img/gen/cat-carboxy-663.webp 663w",
      jpg: "/img/gen/cat-carboxy-480.jpg 480w, /img/gen/cat-carboxy-663.jpg 663w",
    },
    fallback: "/img/gen/cat-carboxy-663.jpg",
  },
  "cat-waxing-ladies": {
    alt: "Gloved hands pressing a wax strip against a client's lower leg",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/cat-waxing-ladies-480.avif 480w, /img/gen/cat-waxing-ladies-800.avif 800w, /img/gen/cat-waxing-ladies-922.avif 922w",
      webp: "/img/gen/cat-waxing-ladies-480.webp 480w, /img/gen/cat-waxing-ladies-800.webp 800w, /img/gen/cat-waxing-ladies-922.webp 922w",
      jpg: "/img/gen/cat-waxing-ladies-480.jpg 480w, /img/gen/cat-waxing-ladies-800.jpg 800w, /img/gen/cat-waxing-ladies-922.jpg 922w",
    },
    fallback: "/img/gen/cat-waxing-ladies-800.jpg",
  },
  "cat-waxing-men": {
    alt: "Gloved hands applying a wax strip along a man's bare back",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/cat-waxing-men-480.avif 480w, /img/gen/cat-waxing-men-800.avif 800w, /img/gen/cat-waxing-men-922.avif 922w",
      webp: "/img/gen/cat-waxing-men-480.webp 480w, /img/gen/cat-waxing-men-800.webp 800w, /img/gen/cat-waxing-men-922.webp 922w",
      jpg: "/img/gen/cat-waxing-men-480.jpg 480w, /img/gen/cat-waxing-men-800.jpg 800w, /img/gen/cat-waxing-men-922.jpg 922w",
    },
    fallback: "/img/gen/cat-waxing-men-800.jpg",
  },
  "fam-hifu-face": {
    alt: "A client with eyes closed in a boucle chair as a gloved hand holds a smooth device to her jaw",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-hifu-face-480.avif 480w, /img/gen/fam-hifu-face-800.avif 800w, /img/gen/fam-hifu-face-922.avif 922w",
      webp: "/img/gen/fam-hifu-face-480.webp 480w, /img/gen/fam-hifu-face-800.webp 800w, /img/gen/fam-hifu-face-922.webp 922w",
      jpg: "/img/gen/fam-hifu-face-480.jpg 480w, /img/gen/fam-hifu-face-800.jpg 800w, /img/gen/fam-hifu-face-922.jpg 922w",
    },
    fallback: "/img/gen/fam-hifu-face-800.jpg",
  },
  "fam-cryotherapy": {
    alt: "A gloved hand holds a slim pen-sized device above a client's hand resting on a towel",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-cryotherapy-480.avif 480w, /img/gen/fam-cryotherapy-800.avif 800w, /img/gen/fam-cryotherapy-922.avif 922w",
      webp: "/img/gen/fam-cryotherapy-480.webp 480w, /img/gen/fam-cryotherapy-800.webp 800w, /img/gen/fam-cryotherapy-922.webp 922w",
      jpg: "/img/gen/fam-cryotherapy-480.jpg 480w, /img/gen/fam-cryotherapy-800.jpg 800w, /img/gen/fam-cryotherapy-922.jpg 922w",
    },
    fallback: "/img/gen/fam-cryotherapy-800.jpg",
  },
  "fam-light-platform": {
    alt: "A client in protective eyewear lies under a blanket as a therapist in eyewear holds a handpiece near her cheek",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-light-platform-480.avif 480w, /img/gen/fam-light-platform-800.avif 800w, /img/gen/fam-light-platform-922.avif 922w",
      webp: "/img/gen/fam-light-platform-480.webp 480w, /img/gen/fam-light-platform-800.webp 800w, /img/gen/fam-light-platform-922.webp 922w",
      jpg: "/img/gen/fam-light-platform-480.jpg 480w, /img/gen/fam-light-platform-800.jpg 800w, /img/gen/fam-light-platform-922.jpg 922w",
    },
    fallback: "/img/gen/fam-light-platform-800.jpg",
  },
  "fam-ipl": {
    alt: "A client in protective eyewear lies back as a therapist in eyewear rests a flat device head on her cheek",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-ipl-480.avif 480w, /img/gen/fam-ipl-800.avif 800w, /img/gen/fam-ipl-922.avif 922w",
      webp: "/img/gen/fam-ipl-480.webp 480w, /img/gen/fam-ipl-800.webp 800w, /img/gen/fam-ipl-922.webp 922w",
      jpg: "/img/gen/fam-ipl-480.jpg 480w, /img/gen/fam-ipl-800.jpg 800w, /img/gen/fam-ipl-922.jpg 922w",
    },
    fallback: "/img/gen/fam-ipl-800.jpg",
  },
  "fam-pico-laser": {
    alt: "Side view of a client in protective eyewear, a gloved hand holding a device head at her temple",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-pico-laser-480.avif 480w, /img/gen/fam-pico-laser-800.avif 800w, /img/gen/fam-pico-laser-922.avif 922w",
      webp: "/img/gen/fam-pico-laser-480.webp 480w, /img/gen/fam-pico-laser-800.webp 800w, /img/gen/fam-pico-laser-922.webp 922w",
      jpg: "/img/gen/fam-pico-laser-480.jpg 480w, /img/gen/fam-pico-laser-800.jpg 800w, /img/gen/fam-pico-laser-922.jpg 922w",
    },
    fallback: "/img/gen/fam-pico-laser-800.jpg",
  },
  "fam-tattoo-removal": {
    alt: "Two women in protective eyewear at a table, a device head held above the client's forearm",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-tattoo-removal-480.avif 480w, /img/gen/fam-tattoo-removal-800.avif 800w, /img/gen/fam-tattoo-removal-922.avif 922w",
      webp: "/img/gen/fam-tattoo-removal-480.webp 480w, /img/gen/fam-tattoo-removal-800.webp 800w, /img/gen/fam-tattoo-removal-922.webp 922w",
      jpg: "/img/gen/fam-tattoo-removal-480.jpg 480w, /img/gen/fam-tattoo-removal-800.jpg 800w, /img/gen/fam-tattoo-removal-922.jpg 922w",
    },
    fallback: "/img/gen/fam-tattoo-removal-800.jpg",
  },
  "fam-gold-microneedling": {
    alt: "A client lying back with eyes closed as a gloved hand rests a pen-shaped device at her cheek",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-gold-microneedling-480.avif 480w, /img/gen/fam-gold-microneedling-800.avif 800w, /img/gen/fam-gold-microneedling-922.avif 922w",
      webp: "/img/gen/fam-gold-microneedling-480.webp 480w, /img/gen/fam-gold-microneedling-800.webp 800w, /img/gen/fam-gold-microneedling-922.webp 922w",
      jpg: "/img/gen/fam-gold-microneedling-480.jpg 480w, /img/gen/fam-gold-microneedling-800.jpg 800w, /img/gen/fam-gold-microneedling-922.jpg 922w",
    },
    fallback: "/img/gen/fam-gold-microneedling-800.jpg",
  },
  "fam-microneedling": {
    alt: "A client lying back with eyes closed, a gloved hand holding a pen-shaped device along her cheek",
    ratio: "4:5",
    width: 663,
    height: 829,
    srcset: {
      avif: "/img/gen/fam-microneedling-480.avif 480w, /img/gen/fam-microneedling-663.avif 663w",
      webp: "/img/gen/fam-microneedling-480.webp 480w, /img/gen/fam-microneedling-663.webp 663w",
      jpg: "/img/gen/fam-microneedling-480.jpg 480w, /img/gen/fam-microneedling-663.jpg 663w",
    },
    fallback: "/img/gen/fam-microneedling-663.jpg",
  },
  "fam-chemical-peel": {
    alt: "A gloved hand brushes a clear liquid across the cheek of a client with eyes closed",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-chemical-peel-480.avif 480w, /img/gen/fam-chemical-peel-800.avif 800w, /img/gen/fam-chemical-peel-922.avif 922w",
      webp: "/img/gen/fam-chemical-peel-480.webp 480w, /img/gen/fam-chemical-peel-800.webp 800w, /img/gen/fam-chemical-peel-922.webp 922w",
      jpg: "/img/gen/fam-chemical-peel-480.jpg 480w, /img/gen/fam-chemical-peel-800.jpg 800w, /img/gen/fam-chemical-peel-922.jpg 922w",
    },
    fallback: "/img/gen/fam-chemical-peel-800.jpg",
  },
  "fam-radiofrequency": {
    alt: "A client lying face down as a gloved hand moves a round device head across her upper back",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-radiofrequency-480.avif 480w, /img/gen/fam-radiofrequency-800.avif 800w, /img/gen/fam-radiofrequency-922.avif 922w",
      webp: "/img/gen/fam-radiofrequency-480.webp 480w, /img/gen/fam-radiofrequency-800.webp 800w, /img/gen/fam-radiofrequency-922.webp 922w",
      jpg: "/img/gen/fam-radiofrequency-480.jpg 480w, /img/gen/fam-radiofrequency-800.jpg 800w, /img/gen/fam-radiofrequency-922.jpg 922w",
    },
    fallback: "/img/gen/fam-radiofrequency-800.jpg",
  },
  "fam-skin-booster-body": {
    alt: "A client in a robe and a therapist holding a folder smile in conversation in a treatment room",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-skin-booster-body-480.avif 480w, /img/gen/fam-skin-booster-body-800.avif 800w, /img/gen/fam-skin-booster-body-922.avif 922w",
      webp: "/img/gen/fam-skin-booster-body-480.webp 480w, /img/gen/fam-skin-booster-body-800.webp 800w, /img/gen/fam-skin-booster-body-922.webp 922w",
      jpg: "/img/gen/fam-skin-booster-body-480.jpg 480w, /img/gen/fam-skin-booster-body-800.jpg 800w, /img/gen/fam-skin-booster-body-922.jpg 922w",
    },
    fallback: "/img/gen/fam-skin-booster-body-800.jpg",
  },
  "fam-skin-booster-face": {
    alt: "Over-the-shoulder view of a consultation, a smiling client facing a woman holding a tablet",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-skin-booster-face-480.avif 480w, /img/gen/fam-skin-booster-face-800.avif 800w, /img/gen/fam-skin-booster-face-922.avif 922w",
      webp: "/img/gen/fam-skin-booster-face-480.webp 480w, /img/gen/fam-skin-booster-face-800.webp 800w, /img/gen/fam-skin-booster-face-922.webp 922w",
      jpg: "/img/gen/fam-skin-booster-face-480.jpg 480w, /img/gen/fam-skin-booster-face-800.jpg 800w, /img/gen/fam-skin-booster-face-922.jpg 922w",
    },
    fallback: "/img/gen/fam-skin-booster-face-800.jpg",
  },
  "fam-skin-booster-hydration": {
    alt: "Two women laughing together on a curved sofa, one holding a glass of water, one a notebook",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-skin-booster-hydration-480.avif 480w, /img/gen/fam-skin-booster-hydration-800.avif 800w, /img/gen/fam-skin-booster-hydration-922.avif 922w",
      webp: "/img/gen/fam-skin-booster-hydration-480.webp 480w, /img/gen/fam-skin-booster-hydration-800.webp 800w, /img/gen/fam-skin-booster-hydration-922.webp 922w",
      jpg: "/img/gen/fam-skin-booster-hydration-480.jpg 480w, /img/gen/fam-skin-booster-hydration-800.jpg 800w, /img/gen/fam-skin-booster-hydration-922.jpg 922w",
    },
    fallback: "/img/gen/fam-skin-booster-hydration-800.jpg",
  },
  "fam-fat-reduction": {
    alt: "A client lying under a towel as a gloved hand adjusts a strap holding a device pad on her thigh",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-fat-reduction-480.avif 480w, /img/gen/fam-fat-reduction-800.avif 800w, /img/gen/fam-fat-reduction-922.avif 922w",
      webp: "/img/gen/fam-fat-reduction-480.webp 480w, /img/gen/fam-fat-reduction-800.webp 800w, /img/gen/fam-fat-reduction-922.webp 922w",
      jpg: "/img/gen/fam-fat-reduction-480.jpg 480w, /img/gen/fam-fat-reduction-800.jpg 800w, /img/gen/fam-fat-reduction-922.jpg 922w",
    },
    fallback: "/img/gen/fam-fat-reduction-800.jpg",
  },
  "fam-muscle-toning": {
    alt: "A relaxed client in cream clothing lying with a device pad strapped over her abdomen",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-muscle-toning-480.avif 480w, /img/gen/fam-muscle-toning-800.avif 800w, /img/gen/fam-muscle-toning-922.avif 922w",
      webp: "/img/gen/fam-muscle-toning-480.webp 480w, /img/gen/fam-muscle-toning-800.webp 800w, /img/gen/fam-muscle-toning-922.webp 922w",
      jpg: "/img/gen/fam-muscle-toning-480.jpg 480w, /img/gen/fam-muscle-toning-800.jpg 800w, /img/gen/fam-muscle-toning-922.jpg 922w",
    },
    fallback: "/img/gen/fam-muscle-toning-800.jpg",
  },
  "fam-hifu-body": {
    alt: "A gloved hand presses a smooth device head against the upper arm of a reclining client",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-hifu-body-480.avif 480w, /img/gen/fam-hifu-body-800.avif 800w, /img/gen/fam-hifu-body-922.avif 922w",
      webp: "/img/gen/fam-hifu-body-480.webp 480w, /img/gen/fam-hifu-body-800.webp 800w, /img/gen/fam-hifu-body-922.webp 922w",
      jpg: "/img/gen/fam-hifu-body-480.jpg 480w, /img/gen/fam-hifu-body-800.jpg 800w, /img/gen/fam-hifu-body-922.jpg 922w",
    },
    fallback: "/img/gen/fam-hifu-body-800.jpg",
  },
  "fam-laser-hair": {
    alt: "A smiling client in protective eyewear, arm raised, as gloved hands hold a device near her underarm",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-laser-hair-480.avif 480w, /img/gen/fam-laser-hair-800.avif 800w, /img/gen/fam-laser-hair-922.avif 922w",
      webp: "/img/gen/fam-laser-hair-480.webp 480w, /img/gen/fam-laser-hair-800.webp 800w, /img/gen/fam-laser-hair-922.webp 922w",
      jpg: "/img/gen/fam-laser-hair-480.jpg 480w, /img/gen/fam-laser-hair-800.jpg 800w, /img/gen/fam-laser-hair-922.jpg 922w",
    },
    fallback: "/img/gen/fam-laser-hair-800.jpg",
  },
  "fam-hydrating-facial": {
    alt: "Hands smoothing a clear sheet mask onto the forehead of a client with eyes closed",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-hydrating-facial-480.avif 480w, /img/gen/fam-hydrating-facial-800.avif 800w, /img/gen/fam-hydrating-facial-922.avif 922w",
      webp: "/img/gen/fam-hydrating-facial-480.webp 480w, /img/gen/fam-hydrating-facial-800.webp 800w, /img/gen/fam-hydrating-facial-922.webp 922w",
      jpg: "/img/gen/fam-hydrating-facial-480.jpg 480w, /img/gen/fam-hydrating-facial-800.jpg 800w, /img/gen/fam-hydrating-facial-922.jpg 922w",
    },
    fallback: "/img/gen/fam-hydrating-facial-800.jpg",
  },
  "fam-sensitive-skin-facial": {
    alt: "Close view of a relaxed client lying back with a pale cream mask on her face",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-sensitive-skin-facial-480.avif 480w, /img/gen/fam-sensitive-skin-facial-800.avif 800w, /img/gen/fam-sensitive-skin-facial-922.avif 922w",
      webp: "/img/gen/fam-sensitive-skin-facial-480.webp 480w, /img/gen/fam-sensitive-skin-facial-800.webp 800w, /img/gen/fam-sensitive-skin-facial-922.webp 922w",
      jpg: "/img/gen/fam-sensitive-skin-facial-480.jpg 480w, /img/gen/fam-sensitive-skin-facial-800.jpg 800w, /img/gen/fam-sensitive-skin-facial-922.jpg 922w",
    },
    fallback: "/img/gen/fam-sensitive-skin-facial-800.jpg",
  },
  "fam-microdermabrasion": {
    alt: "Gloved hands laying a folded cream cloth across the forehead of a relaxed client",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-microdermabrasion-480.avif 480w, /img/gen/fam-microdermabrasion-800.avif 800w, /img/gen/fam-microdermabrasion-922.avif 922w",
      webp: "/img/gen/fam-microdermabrasion-480.webp 480w, /img/gen/fam-microdermabrasion-800.webp 800w, /img/gen/fam-microdermabrasion-922.webp 922w",
      jpg: "/img/gen/fam-microdermabrasion-480.jpg 480w, /img/gen/fam-microdermabrasion-800.jpg 800w, /img/gen/fam-microdermabrasion-922.jpg 922w",
    },
    fallback: "/img/gen/fam-microdermabrasion-800.jpg",
  },
  "fam-botanical-facial": {
    alt: "A seated therapist resting her hands on a client's shoulders at the start of a facial",
    ratio: "4:5",
    width: 922,
    height: 1152,
    srcset: {
      avif: "/img/gen/fam-botanical-facial-480.avif 480w, /img/gen/fam-botanical-facial-800.avif 800w, /img/gen/fam-botanical-facial-922.avif 922w",
      webp: "/img/gen/fam-botanical-facial-480.webp 480w, /img/gen/fam-botanical-facial-800.webp 800w, /img/gen/fam-botanical-facial-922.webp 922w",
      jpg: "/img/gen/fam-botanical-facial-480.jpg 480w, /img/gen/fam-botanical-facial-800.jpg 800w, /img/gen/fam-botanical-facial-922.jpg 922w",
    },
    fallback: "/img/gen/fam-botanical-facial-800.jpg",
  },
};
